### ISSUE TITLE
ZIP, EZIP, XZIP and YZIP internal Infocom documentation

### ISSUE THREAD

**Issue by heasm66** [cschweda/awesome-z-machine#3]
All transcribed pdf-versions, the YZIP by me.

ZIP - https://github.com/heasm66/ZIL-Resources/blob/master/spec-zip.pdf
EZIP - https://github.com/heasm66/ZIL-Resources/blob/master/spec-ezip.pdf
XZIP - https://github.com/heasm66/ZIL-Resources/blob/master/spec-xzip.pdf
YZIP - https://github.com/heasm66/YZIP-Specifications/blob/master/yzip%20specifications.pdf

**Comment by cschweda** [comment]
Thanks!

Added in 64b25cf6589d724109bca9d9947ba79e7a563026
